Inst: insurer crashgroup emergencyServices motorwaymanagement
Agent: centralMember1 centralMember2
Victim: victim1 victim2
InsuranceState: valid invalid
CrimeType: noInsurance leftScene
PoliceUnit: policeUnit1 policeUnit2
CollisionLaneMember: centralMember3 centralMember4 centralMember5 centralMember6 centralMember7
FreeLaneMember: centralMember3 centralMember4 centralMember5 centralMember6 centralMember7
