#!/bin/bash
 alias ejabberdctl='./ejabberdctl'
if [ $# -eq 1 ]
then
echo creating users for $1
./ejabberdctl register	ardrone1	 $1 jasonpassword
./ejabberdctl register	ardrone1-sender	 $1 jasonpassword
./ejabberdctl register	ardrone1-vehicle	 $1 jasonpassword
./ejabberdctl register	ardrone1-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	ardrone1-vehicle-simsender	 $1 jasonpassword
./ejabberdctl register	central	 $1 jasonpassword
./ejabberdctl register	central-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember1	 $1 jasonpassword
./ejabberdctl register	centralmember1-inst-sender	 $1 jasonpassword
./ejabberdctl register	centralmember1-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember1-sender	 $1 jasonpassword
./ejabberdctl register	centralmember1-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember1-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember1push	 $1 jasonpassword
./ejabberdctl register	centralmember1push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember1push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember1push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember1push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember2	 $1 jasonpassword
./ejabberdctl register	centralmember2-inst-sender	 $1 jasonpassword
./ejabberdctl register	centralmember2-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember2-sender	 $1 jasonpassword
./ejabberdctl register	centralmember2-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember2-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember2push	 $1 jasonpassword
./ejabberdctl register	centralmember2push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember2push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember2push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember2push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember3	 $1 jasonpassword
./ejabberdctl register	centralmember3-inst-sender	 $1 jasonpassword
./ejabberdctl register	centralmember3-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember3-sender	 $1 jasonpassword
./ejabberdctl register	centralmember3-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember3-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember3push	 $1 jasonpassword
./ejabberdctl register	centralmember3push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember3push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember3push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember3push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember4	 $1 jasonpassword
./ejabberdctl register	centralmember4-inst-sender	 $1 jasonpassword
./ejabberdctl register	centralmember4-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember4-sender	 $1 jasonpassword
./ejabberdctl register	centralmember4-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember4-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmember4push	 $1 jasonpassword
./ejabberdctl register	centralmember4push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember4push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember4push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember4push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register  centralmember5   $1 jasonpassword
./ejabberdctl register  centralmember5-inst-sender       $1 jasonpassword
./ejabberdctl register  centralmember5-jstate    $1 jasonpassword
./ejabberdctl register  centralmember5-sender    $1 jasonpassword
./ejabberdctl register  centralmember5-vehicle   $1 jasonpassword
./ejabberdctl register  centralmember5-vehicle-receiver  $1 jasonpassword
./ejabberdctl register	centralmember5push	 $1 jasonpassword
./ejabberdctl register	centralmember5push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember5push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember5push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember5push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register  centralmember6   $1 jasonpassword
./ejabberdctl register  centralmember6-inst-sender       $1 jasonpassword
./ejabberdctl register  centralmember6-jstate    $1 jasonpassword
./ejabberdctl register  centralmember6-sender    $1 jasonpassword
./ejabberdctl register  centralmember6-vehicle   $1 jasonpassword
./ejabberdctl register  centralmember6-vehicle-receiver  $1 jasonpassword
./ejabberdctl register	centralmember6push	 $1 jasonpassword
./ejabberdctl register	centralmember6push-jstate	 $1 jasonpassword
./ejabberdctl register	centralmember6push-sender	 $1 jasonpassword
./ejabberdctl register	centralmember6push-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmember6push-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmemberardrone1	 $1 jasonpassword
./ejabberdctl register	centralmemberardrone1-jstate	 $1 jasonpassword
./ejabberdctl register	centralmemberardrone1-sender	 $1 jasonpassword
./ejabberdctl register	centralmemberardrone1-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmemberardrone1-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	centralmembertest	 $1 jasonpassword
./ejabberdctl register	centralmembertest-jstate	 $1 jasonpassword
./ejabberdctl register	centralmembertest-jstate-rec	 $1 jasonpassword
./ejabberdctl register	centralmembertest-sender	 $1 jasonpassword
./ejabberdctl register	centralmembertest-vehicle	 $1 jasonpassword
./ejabberdctl register	centralmembertest-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	debug	 $1 jasonpassword
./ejabberdctl register	debug-client	 $1 jasonpassword
./ejabberdctl register	debug-sender	 $1 jasonpassword
./ejabberdctl register	examplepublisher	 $1 jasonpassword
./ejabberdctl register	examplesubscriber	 $1 jasonpassword
./ejabberdctl register	instbot	 $1 jasonpassword
./ejabberdctl register	instmanager	 $1 jasonpassword
./ejabberdctl register	jsonexamplepublisher	 $1 jasonpassword
./ejabberdctl register	jsonexamplesubscriber	 $1 jasonpassword
./ejabberdctl register	rdfmonitor	 $1 jasonpassword
./ejabberdctl register	rdfreplay	 $1 jasonpassword
./ejabberdctl register	rdfreplaysimstatesender	 $1 jasonpassword
./ejabberdctl register	rdftest	 $1 jasonpassword
./ejabberdctl register	rdftest-jstate	 $1 jasonpassword
./ejabberdctl register	rdftest-jstate-rec	 $1 jasonpassword
./ejabberdctl register	rdftest-sender	 $1 jasonpassword
./ejabberdctl register	rdftest-simsender	 $1 jasonpassword
./ejabberdctl register	rdftest-vehicle	 $1 jasonpassword
./ejabberdctl register	rdftest-vehicle-receiver	 $1 jasonpassword
./ejabberdctl register	sumo	 $1 jasonpassword
./ejabberdctl register	sumo-sender	 $1 jasonpassword
./ejabberdctl register	sumo-receiver	 $1 jasonpassword
./ejabberdctl register	sumo-inst-sender	 $1 jasonpassword
./ejabberdctl register	triplestore	 $1 jasonpassword
./ejabberdctl register	triplestore-jstate	 $1 jasonpassword
./ejabberdctl register	xmppsimsender	 $1 jasonpassword
./ejabberdctl register	xmppsimsender-jstate	 $1 jasonpassword
./ejabberdctl register	xmppviewer	 $1 jasonpassword
./ejabberdctl register	xmppviewer-inst	 $1 jasonpassword
./ejabberdctl register	xmppviewerjstate	 $1 jasonpassword
./ejabberdctl register	xmppviewersimstate	 $1 jasonpassword
./ejabberdctl register	xmppviewersimstatesender	 $1 jasonpassword
./ejabberdctl register	xmppworld	 $1 jasonpassword
./ejabberdctl register	xmppworldinstclient	 $1 jasonpassword
./ejabberdctl register	AOI	 $1 jasonpassword
./ejabberdctl register	AOI-receiver	 $1 jasonpassword
./ejabberdctl register	AOI-sender	 $1 jasonpassword
./ejabberdctl register piSensor1-sender $1 jasonpassword
./ejabberdctl register piSensor1-receiver $1 jasonpassword
./ejabberdctl register hueBSF-receiver $1 jasonpassword
./ejabberdctl register hueBSF-sender $1 jasonpassword
./ejabberdctl register hueBSF $1 jasonpassword
./ejabberdctl register tivo $1 jasonpassword
./ejabberdctl register tivo-sender $1 jasonpassword
./ejabberdctl register tivo-receiver $1 jasonpassword
./ejabberdctl register asterisk $1 jasonpassword
./ejabberdctl register asterisk-sender $1 jasonpassword
./ejabberdctl register asterisk-receiver $1 jasonpassword
./ejabberdctl register faceRecogition $1 jasonpassword
./ejabberdctl register faceRecogition-sender $1 jasonpassword
./ejabberdctl register faceRecogition-receiver $1 jasonpassword
./ejabberdctl register motionTracker $1 jasonpassword
./ejabberdctl register motionTracker-sender $1 jasonpassword
./ejabberdctl register motionTracker-receiver $1 jasonpassword

fi

